frontend/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns
from frontend import views


urlpatterns = [
    path('', views.index),
    path('device/', views.devices),
    path('newdevice/', views.devices_new)
]

urlpatterns = format_suffix_patterns(urlpatterns)

nuaal_web/urls.py
from django.contrib import admin
from django.urls import path, include
from nuaal_api import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('nuaal_api.urls')),
    path('topology/', include('topology.urls')),
    path('', include('frontend.urls'))

]

frontend/models.py
from django.db import models

# Create your models here.

nuaal_api/models.py
from django.db import models
import uuid
import socket
from nuaal.utils import int_name_convert
# Create your models here.


class Site(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    siteShortName = models.CharField(max_length=30, default="")
    siteLongName = models.CharField(max_length=30, default="")
    address = models.CharField(max_length=120, default="")

    def __str__(self):
        return "{} ({})".format(self.siteLongName, self.siteShortName)


class Device(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    hostname = models.CharField(max_length=30, default="")
    managementIp = models.CharField(max_length=15, default="")
    vendor = models.CharField(max_length=30, default="")
    platform = models.CharField(max_length=30, default="")
    sw = models.CharField(max_length=30, default="")
    swVersion = models.CharField(max_length=30, default="")
    site = models.ForeignKey(Site, on_delete=models.CASCADE)
    role = models.CharField(max_length=30, default="unknown", choices=(
        ("host", "Host"),
        ("accesspoint", "Access Point"),
        ("access", "Access"),
        ("distribution", "Distribution"),
        ("core", "Core"),
        ("unknown", "Unknown")
    ))
    deviceFamily = models.CharField(max_length=30, default="unknown", choices=(
        ("switch", "Switch"),
        ("router", "Router"),
        ("accesspoint", "Access Point"),
        ("unknown", "Unknown"),
    ))
    deviceType = models.CharField(max_length=30, default="unknown", choices=(
        ("fix", "Fix"),
        ("modular", "Modular"),
        ("stack", "Stack"),
        ("accesspoint", "Access Point"),
        ("unknown", "Unknown"),
    ))
    interfaceCount = models.IntegerField(default=0)
    eoxStatus = models.CharField(max_length=30, default="unknown", choices=(
        ("EoL", "End of Life"),
        ("OK", "No EoX"),
        ("unknown", "Unknown")
    ))

    def __str__(self):
        return "{} ({}/{})".format(self.hostname, self.vendor, self.platform)

    def _get_links(self):
        return self.sourceDevice.all() | self.targetDevice.all()

    def _get_link_count(self):
        return len(self._get_links())

    def get_neighbors(self):
        links = self._get_links()
        neighbors = []
        for link in links:
            if link.sourceDevice not in neighbors:
                neighbors.append(link.sourceDevice)
            if link.targetDevice not in neighbors:
                neighbors.append(link.targetDevice)
        try:
            neighbors.remove(self)
        except ValueError:
            pass
        finally:
            return neighbors

    def get_neighbors_count(self):
        return len(self.get_neighbors())

class Link(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    sourceDevice = models.ForeignKey(Device, related_name="sourceDevice", on_delete=models.CASCADE)
    sourceInterface = models.CharField(max_length=20, default="")
    targetDevice = models.ForeignKey(Device, related_name="targetDevice", on_delete=models.CASCADE)
    targetInterface = models.CharField(max_length=20, default="")
    linkType = models.CharField(max_length=10, default="unknown", choices=(
        ("base-t", "Base-T"),
        ("multimode", "Multi-Mode"),
        ("singlemode", "Single-Mode"),
        ('twinax', "Twinax"),
        ("unknown", "Unknown")
    ))

    def get_interfaces(self):
        return self.sourceDevice.interface_set.filter(nameLong=self.sourceInterface) | self.targetDevice.interface_set.filter(nameLong=self.targetInterface)

    def get_sourceInterface(self):
        try:
            return self.sourceDevice.interface_set.get(nameLong=self.sourceInterface)
        except Exception as e:
            print(repr(e))
            return None

    def __str__(self):
        return "{} ({}) - {} ({})".format(
            int_name_convert(self.sourceInterface),
            self.sourceDevice.hostname,
            int_name_convert(self.targetInterface),
            self.targetDevice.hostname
        )


class Interface(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    nameLong = models.CharField(max_length=30, default="")
    nameShort = models.CharField(max_length=30, default="")
    description = models.CharField(max_length=30, default="")
    interfaceFamily = models.CharField(max_length=30, default="unknown", choices=(
        ("physical", "Physical"),
        ("virtual", "Virtual"),
        ("etherchannel", "EtherChannel"),
        ("unknown", "Unknown")
    ))
    interfaceType = models.CharField(max_length=30, default="unknown")
    device = models.ForeignKey(Device, on_delete=models.CASCADE)

    def __str__(self):
        return "{} on {}".format(self.nameLong, str(self.device.hostname))


class Inventory(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    device = models.ForeignKey(Device, on_delete=models.CASCADE)
    name = models.CharField(max_length=120, default="")
    desc = models.CharField(max_length=120, default="")
    pid = models.CharField(max_length=40, default="")
    vid = models.CharField(max_length=40, default="")
    sn = models.CharField(max_length=40, default="")

frontend/views.py
from django.shortcuts import render, HttpResponse
from django.template.loader import render_to_string
from nuaal_api.models import Device
import os
import json

# Create your views here.
def index(request):
    context = Device.objects.all()
    return render(request=request, template_name="frontend/index.html", context={"devices": context})

def devices(request):
    device_qs = Device.objects.all()
    context = {"devices": device_qs}
    content_string = render_to_string(template_name="frontend/data_json.jinja2", context=context)
    filepath = os.path.join(os.path.dirname(os.path.abspath(__file__)), "static", "frontend", "data.json")
    with open(file=filepath, mode="w") as f:
        f.write(content_string)
    return render(request=request, template_name="frontend/devices.html", context=context)

def devices_new(request):
    return render(request=request, template_name="frontend/new_devices.html")

frontend/templates/frontend/data_json.jinja2
[
    {% for device in devices %}
    {
    "hostname": "{{ device.hostname }}",
    "site": "{{ device.site.siteShortName }}",
    "platform": "{{ device.platform }}",
    "deviceFamily": "{{ device.get_deviceFamily_display }}",
    "deviceRole": "{{ device.get_role_display }}",
    "interfaceCount": "{{ device.interfaceCount }}"
    }{% if not forloop.last %},{% endif %}{% endfor %}
]

frontend/templates/frontend/devices.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Bootstrap Table - Filter control</title>


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel='stylesheet' href='http://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.10.0/bootstrap-table.min.css'>
    <link rel='stylesheet'
          href='http://rawgit.com/vitalets/x-editable/master/dist/bootstrap3-editable/css/bootstrap-editable.css'>


</head>

<body>
<script>
function LinkFormatter(value, row, index) {
	return '<a href="/admin/' + row.device + '/' + index + '">' + value + '<a>';
}
</script>

<div class="container-fluid">
    <h1>Devices MHMP</h1>


    <table id="table"
           data-toggle="table"
           data-search="true"
           data-filter-control="true"
           data-show-export="true"
           data-click-to-select="true"
           data-toolbar="#toolbar"
           class="table table-striped table-bordered table-sm">
        <thead>
        <tr>
            <th data-field="device" data-filter-control="input" data-formatter="LinkFormatter" data-sortable="true">Hostname</th>
            <th data-field="site" data-filter-control="select" data-sortable="true">Site</th>
            <th data-field="platform" data-filter-control="input" data-sortable="true">Platform</th>
            <th data-field="family" data-filter-control="input" data-sortable="true">Device Family</th>
            <th data-field="role" data-filter-control="select" data-sortable="true">Device Role</th>
            <th data-field="intcount" data-filter-control="input" data-sortable="true">Interface Count</th>
        </tr>
        </thead>
        <tbody>
        {% for device in devices %}
        <tr>
            <td>{{ device.hostname }}</td>
            <td>{{ device.site.siteShortName }}</td>
            <td>{{ device.platform }}</td>
            <td>{{ device.get_deviceFamily_display }}</td>
            <td>{{ device.get_role_display }}</td>
            <td>{{ device.interfaceCount }}</td>
        </tr>
        {% endfor %}
        </tbody>
        <tfoot>
        <tr>
            <th>Hostname
            </th>
            <th>Site
            </th>
            <th>Platform
            </th>
            <th>Device Family
            </th>
            <th>Device Type
            </th>
            <th>Interface Count
            </th>
        </tr>
        </tfoot>
    </table>
</div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
<script src='http://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.10.0/bootstrap-table.js'></script>
<script src='http://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.9.1/extensions/editable/bootstrap-table-editable.js'></script>
<script src='http://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.9.1/extensions/filter-control/bootstrap-table-filter-control.js'></script>



</body>

</html>

frontend/templates/frontend/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
</head>
<body>

<div class="container-fluid">
    <h1>NUAAL WEB</h1>
    <p>MHMP</p>

    <table id="dtBasicExample" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
        <thead>
        <tr>
            <th class="th-sm">Hostname
                <i class="fa fa-sort float-right" aria-hidden="true"></i>
            </th>
            <th class="th-sm">Site
                <i class="fa fa-sort float-right" aria-hidden="true"></i>
            </th>
            <th class="th-sm">Platform
                <i class="fa fa-sort float-right" aria-hidden="true"></i>
            </th>
            <th class="th-sm">Device Family
                <i class="fa fa-sort float-right" aria-hidden="true"></i>
            </th>
            <th class="th-sm">Device Type
                <i class="fa fa-sort float-right" aria-hidden="true"></i>
            </th>
            <th class="th-sm">Interface Count
                <i class="fa fa-sort float-right" aria-hidden="true"></i>
            </th>
        </tr>
        </thead>
        <tbody>
        {% for device in devices %}
            <tr>
                <td>{{ device.hostname }}</td>
                <td>{{ device.site.siteShortName }}</td>
                <td>{{ device.platform }}</td>
                <td>{{ device.get_deviceFamily_display }}</td>
                <td>{{ device.get_role_display }}</td>
                <td>{{ device.interfaceCount }}</td>
            </tr>{% endfor %}
        </tbody>
        <tfoot>
        <tr>
            <th>Hostname
            </th>
            <th>Site
            </th>
            <th>Platform
            </th>
            <th>Device Family
            </th>
            <th>Device Type
            </th>
            <th>Interface Count
            </th>
        </tr>
        </tfoot>
    </table>
</div>

</body>
</html>

frontend/templates/frontend/new_devices.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Bootstrap Table - Filter control</title>


    <link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css'>
    <link rel='stylesheet' href='http://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.10.0/bootstrap-table.min.css'>
    <link rel='stylesheet' href='http://rawgit.com/vitalets/x-editable/master/dist/bootstrap3-editable/css/bootstrap-editable.css'>

</head>

<body>

<div class="container-fluid">
    <h1>Bootstrap Table</h1>

    <table id="table"
           data-toggle="table"
           data-search="true"
           data-filter-control="true"
           data-show-export="true"
           data-click-to-select="true"
           data-toolbar="#toolbar"
           data-url="/api/device/?format=json"
           class="table table-striped table-bordered table-sm">
        <thead>
            <tr>
                <th data-field="hostname" data-filter-control="input" data-sortable="true" data-formatter="linkFormatter">Hostname</th>
                <th data-field="site" data-filter-control="select" data-sortable="true">Site</th>
                <th data-field="platform" data-filter-control="input" data-sortable="true">Platform</th>
                <th data-field="deviceFamily" data-filter-control="select" data-sortable="true">Device Family</th>
                <th data-field="role" data-filter-control="select" data-sortable="true">Device Role</th>
                <th data-field="interfaceCount" data-filter-control="input" data-sortable="true">Interface Count</th>
            </tr>
        </thead>
    </table>
</div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
<script src='http://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.10.0/bootstrap-table.js'></script>
<script src='http://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.9.1/extensions/editable/bootstrap-table-editable.js'></script>
<script src='http://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.9.1/extensions/filter-control/bootstrap-table-filter-control.js'></script>
<!--<script>

$('#table').bootstrapTable({
    // url: 'https://api.myjson.com/bins/khye2',
    url: '/api/device/?format=json',
    columns: [
        {
            field: 'hostname',
            title: 'Hostname'
        },
        {
            field: 'site',
            title: 'Site'
        },
        {
            field: 'platform',
            title: 'Platform'
        },
    ]
});
</script>-->
<script>
function linkFormatter(value, row) {
  return "<a href='/admin/nuaal_api/device/" + row.id + "'>" + value + "</a>";
}
</script>
</body>

</html>